### ISSUE TITLE
What are the minimum necessary permissions?

### ISSUE THREAD

**Issue by zwiebelspaetzle** [madrisan/hashicorp-vault-monitor#4]
The readme uses the root token of a dev setup.  In prod, what are the minimum permissions needed for this script to run?

**Comment by madrisan** [comment]
For reading secrets (`get`) and monitor the token expiration (`token-lookup`) you do not need a root token.
In general you just need a token associated to a policy just allowing the actions you need.
For instance the `get` command need a token able to read in a sub-tree of `secret/`.

**Comment by madrisan** [comment]
It's not necessary to execute this binary as root, only a simple execution right.
